apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-dashboard

spec:
  replicas: 3

  selector:
    matchLabels:
      app: price-dashboard

  template:
    metadata:
      labels:
        app: price-dashboard

    spec:
      containers:
      - name: price-dashboard
        image: YOUR_DOCKER_USERNAME/price-dashboard:latest
        ports:
        - containerPort: 8501